# Generated by Django 3.2.4 on 2023-07-05 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=128, null=True)),
                ('question_type', models.CharField(blank=True, choices=[('sign', 'Sign'), ('rule', 'Rule')], max_length=128, null=True)),
                ('question', models.CharField(max_length=256)),
                ('option', models.CharField(max_length=256)),
                ('answer', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UserPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_challanged', models.BooleanField(default=False)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('practice_test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_practice_test', to='practicetest.practicetest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_practice_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
