# Generated by Django 3.2.4 on 2023-07-13 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('practicetest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicetest',
            name='content',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='practice_test_content', to='content.content'),
            preserve_default=False,
        ),
    ]
