# Generated by Django 3.2.4 on 2023-07-13 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('practicetest', '0002_practicetest_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicetest',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='practice_test_content', to='content.content'),
        ),
        migrations.AlterField(
            model_name='practicetest',
            name='question',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
