# Generated by Django 3.2.4 on 2023-07-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicetest', '0004_practicetest_is_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicetest',
            name='is_note',
        ),
        migrations.AlterField(
            model_name='practicetest',
            name='question_type',
            field=models.CharField(blank=True, choices=[('sign', 'Sign'), ('rule', 'Rule'), ('note', 'note')], max_length=128, null=True),
        ),
    ]
