# Generated by Django 3.2.4 on 2023-07-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20230705_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
